language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install pillow
  - pip install coverage
  - pip install cython

script:
  # Pure python mode
  - nosetests code --with-coverage --cover-package=png
  # Cython accelerated
  - python setup.py build_ext --inplace
  - nosetests code --with-coverage --cover-package=png
